baseURL = "http://www.nordix.io/"
languageCode = "en-us"
title = "Nordix Foundation"
disableKinds = [ "RSS", "sitemap" ]

[[menu.main]]
    name = "About"
    url = "/"
[[menu.main]]
    name = "Join"
    url = "/join/"
[[menu.main]]
    name = "News"
    url = "/news/"

[outputs]
  home = [ "HTML", "CSS" ]

[taxonomies]
  tag = ""
  category = ""
